name: Pruebas

on:
    push:
        paths: ['**.yml', '**.py']

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Descargar repo
              uses: actions/checkout@v3
            
            - name: Instalar Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            
            - name: Instalar dependencias
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Ejecutar pruebas
              run: pytest -v
