name: Pruebas

on:
    push:
        paths: ['**.yml', '**.py']

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Descargar repo
              uses: actions/checkout@v3
            
            - name: Instalar Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            
            - name: Instalar dependencias
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Ejecutar pruebas
              run: pytest -v --junit-xml=test-results.xml # el siguiente paso necesita los resultados en formato XML
            
            - name: Mostrar resultados
              if: always()
              uses: pmeier/pytest-results-action@v0.3.0
              with:
                path: test-results.xml
